name = "portfolio-visits"
main = "src/index.ts"
compatibility_date = "2026-10-01"

[vars]
ALLOWED_ORIGINS = "https://91tleg.github.io,http://localhost:4321"

[[kv_namespaces]]
binding = "VISITS"
id = "aeee623b495e4a30b9d679aea0f006f9"
